#############################################################################
# Generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#  Mar 24, 2021 02:49:32 PM IST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m49" -background #000040 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 1280x686+212+135
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3004 1913
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Search" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    menu $top.m49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    ttk::separator $top.tSe97 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe97" "TSeparator3" vTcl:WidgetProc "Search" 1
    ttk::separator $top.tSe100 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe100" "TSeparator4" vTcl:WidgetProc "Search" 1
    button $top.but61 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #95f1f7 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 23 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Add 
    vTcl:DefineAlias "$top.but61" "Add_b" vTcl:WidgetProc "Search" 1
    button $top.but62 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ff8040 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 23 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Modify 
    vTcl:DefineAlias "$top.but62" "Modify_b" vTcl:WidgetProc "Search" 1
    button $top.but63 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #d32c38 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 23 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Delete 
    vTcl:DefineAlias "$top.but63" "Delete_b" vTcl:WidgetProc "Search" 1
    button $top.but64 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #b3ffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text User 
    vTcl:DefineAlias "$top.but64" "User_b" vTcl:WidgetProc "Search" 1
    button $top.but65 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #57fd53 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 17 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Movie 
    vTcl:DefineAlias "$top.but65" "Movie_b" vTcl:WidgetProc "Search" 1
    button $top.but67 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #d382ee -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 17 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Cinema 
    vTcl:DefineAlias "$top.but67" "Cinema_b" vTcl:WidgetProc "Search" 1
    button $top.but68 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #660455 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 17 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text Show 
    vTcl:DefineAlias "$top.but68" "Show_b" vTcl:WidgetProc "Search" 1
    button $top.but69 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #b71730 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 18 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text <Back 
    vTcl:DefineAlias "$top.but69" "Back_b" vTcl:WidgetProc "Search" 1
    label $top.lab70 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Label 
    vTcl:DefineAlias "$top.lab70" "Logo_image" vTcl:WidgetProc "Search" 1
    label $top.lab71 \
        -background #000040 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 22 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -text {Theatre Buzz Admin Page} 
    vTcl:DefineAlias "$top.lab71" "Title_l" vTcl:WidgetProc "Search" 1
    label $top.lab72 \
        -background #000040 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #aafbfb -text >> 
    vTcl:DefineAlias "$top.lab72" "Label2" vTcl:WidgetProc "Search" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tSe97 \
        -in $top -x 0 -relx 0.165 -y 0 -rely 0.167 -width 0 -relwidth 0.001 \
        -height 0 -relheight 0.846 -anchor nw -bordermode inside 
    place $top.tSe100 \
        -in $top -x 0 -relx 0.818 -y 0 -rely 0.167 -width 0 -relwidth 0.001 \
        -height 0 -relheight 0.836 -anchor nw -bordermode inside 
    place $top.but61 \
        -in $top -x 0 -relx 0.211 -y 0 -rely 0.204 -width 247 -relwidth 0 \
        -height 104 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but62 \
        -in $top -x 0 -relx 0.211 -y 0 -rely 0.423 -width 247 -relwidth 0 \
        -height 114 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but63 \
        -in $top -x 0 -relx 0.211 -y 0 -rely 0.641 -width 247 -relwidth 0 \
        -height 124 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but64 \
        -in $top -x 0 -relx 0.633 -y 0 -rely 0.175 -width 177 -relwidth 0 \
        -height 84 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but65 \
        -in $top -x 0 -relx 0.633 -y 0 -rely 0.335 -width 177 -relwidth 0 \
        -height 84 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but67 \
        -in $top -x 0 -relx 0.633 -y 0 -rely 0.496 -width 177 -relwidth 0 \
        -height 84 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but68 \
        -in $top -x 0 -relx 0.633 -y 0 -rely 0.656 -width 177 -relwidth 0 \
        -height 84 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but69 \
        -in $top -x 0 -relx 0.648 -y 0 -rely 0.845 -width 147 -relwidth 0 \
        -height 64 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab70 \
        -in $top -x 0 -relx 0.172 -y 0 -rely 0.015 -width 0 -relwidth 0.097 \
        -height 0 -relheight 0.133 -anchor nw -bordermode ignore 
    place $top.lab71 \
        -in $top -x 0 -relx 0.32 -y 0 -rely 0.044 -width 0 -relwidth 0.291 \
        -height 0 -relheight 0.089 -anchor nw -bordermode ignore 
    place $top.lab72 \
        -in $top -x 0 -relx 0.484 -y 0 -rely 0.452 -width 0 -relwidth 0.073 \
        -height 0 -relheight 0.133 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

