#############################################################################
# Generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#  Mar 23, 2021 04:11:10 PM IST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { \
    bg_png "./bg.png" \
}
vTcl:create_project_images $image_list   ;# In image.tcl


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m49" -background #000040 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 1280x686+297+168
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3004 1913
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    menu $top.m49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    labelframe $top.lab55 \
        -font TkDefaultFont -foreground #edea67 -background #bfe2ff \
        -height 354 -highlightbackground #f3fee2 -highlightcolor #4bc602 \
        -width 179 
    vTcl:DefineAlias "$top.lab55" "Membership_f" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab55
    button $site_3_0.but56 \
        -activebackground #707070 -activeforeground #000000 \
        -background #d8d8d8 -borderwidth 9 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 15 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Platinum 
    vTcl:DefineAlias "$site_3_0.but56" "Platinum_b" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but57 \
        -activebackground #f0df99 -activeforeground #000000 \
        -background #ffda04 -borderwidth 9 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 15 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Gold 
    vTcl:DefineAlias "$site_3_0.but57" "Gold_b" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but58 \
        -activebackground #d9fcff -activeforeground #7070fa \
        -background #2de9f2 -borderwidth 9 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 15 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor #e9f552 \
        -highlightthickness 6 -pady 0 -text Diamond 
    vTcl:DefineAlias "$site_3_0.but58" "Diamond_b" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab60 \
        -activebackground #f9f9f9 -activeforeground black -background #bfe2ff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Join our Membership plan!} -wraplength 150 
    vTcl:DefineAlias "$site_3_0.lab60" "Label1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but56 \
        -in $site_3_0 -x 0 -relx 0.059 -y 0 -rely 0.452 -width 157 \
        -relwidth 0 -height 84 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but57 \
        -in $site_3_0 -x 0 -relx 0.059 -y 0 -rely 0.734 -width 157 \
        -relwidth 0 -height 84 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but58 \
        -in $site_3_0 -x 0 -relx 0.059 -y 0 -rely 0.169 -width 157 \
        -relwidth 0 -height 84 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 0 -relx 0.056 -y 0 -rely 0.028 -width 0 \
        -relwidth 0.866 -height 0 -relheight 0.116 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab62 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -background #e8e8ff -height 100 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 600 
    vTcl:DefineAlias "$top.lab62" "Home_f" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab62
    frame $site_3_0.fra66 \
        -borderwidth 2 -relief groove -background #b3eaff -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 545 
    vTcl:DefineAlias "$site_3_0.fra66" "home_inner_f" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra66
    button $site_4_0.but67 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #000040 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text Home 
    vTcl:DefineAlias "$site_4_0.but67" "Home_b" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab68 \
        -activebackground #b3eaff -activeforeground black -background #b3eaff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Membership status} 
    vTcl:DefineAlias "$site_4_0.lab68" "Member_l" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.but67 \
        -in $site_4_0 -x 0 -relx 0.025 -y 0 -width 77 -relwidth 0 -height 54 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab68 \
        -in $site_4_0 -x 0 -relx 0.261 -y 0 -rely 0.133 -width 0 \
        -relwidth 0.668 -height 0 -relheight 0.68 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $site_3_0.fra66
    place $site_3_0.fra66 \
        -in $site_3_0 -x 0 -relx 0.017 -y 0 -rely 0.106 -width 0 \
        -relwidth 0.958 -height 0 -relheight 0.798 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab74 \
        -font TkDefaultFont -foreground black -background #e8e8ff -height 41 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 412 
    vTcl:DefineAlias "$top.lab74" "Labelframe3" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab74
    button $site_3_0.but75 \
        -activebackground #b3eaff -activeforeground #000000 \
        -background #00205b -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text Search 
    vTcl:DefineAlias "$site_3_0.but75" "Search_b" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent77 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 304 
    vTcl:DefineAlias "$site_3_0.ent77" "Search_e" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but75 \
        -in $site_3_0 -x 0 -y 0 -width 87 -relwidth 0 -height 44 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $site_3_0.ent77 \
        -in $site_3_0 -x 0 -relx 0.267 -y 0 -width 304 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    label $top.lab78 \
        -activebackground #f9f9f9 -activeforeground black -background #000040 \
        -borderwidth 5 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 22 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text Recommended! 
    vTcl:DefineAlias "$top.lab78" "Label3" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe97 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe97" "TSeparator3" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe100 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe100" "TSeparator4" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab47 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -image bg_png \
        -text Label 
    vTcl:DefineAlias "$top.lab47" "Label2" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab55 \
        -in $top -x 0 -relx 0.013 -y 0 -rely 0.219 -width 0 -relwidth 0.14 \
        -height 0 -relheight 0.516 -anchor nw -bordermode ignore 
    place $top.lab62 \
        -in $top -x 0 -relx 0.023 -y 0 -rely 0.029 -width 0 -relwidth 0.32 \
        -height 0 -relheight 0.093 -anchor nw -bordermode ignore 
    place $top.lab74 \
        -in $top -x 0 -relx 0.609 -y 0 -rely 0.044 -width 0 -relwidth 0.322 \
        -height 0 -relheight 0.06 -anchor nw -bordermode ignore 
    place $top.lab78 \
        -in $top -x 0 -relx 0.172 -y 0 -rely 0.131 -width 0 -relwidth 0.159 \
        -height 0 -relheight 0.07 -anchor nw -bordermode ignore 
    place $top.tSe97 \
        -in $top -x 0 -relx 0.165 -y 0 -rely 0.167 -width 0 -relwidth 0.001 \
        -height 0 -relheight 0.846 -anchor nw -bordermode inside 
    place $top.tSe100 \
        -in $top -x 0 -relx 0.818 -y 0 -rely 0.167 -width 0 -relwidth 0.001 \
        -height 0 -relheight 0.836 -anchor nw -bordermode inside 
    place $top.lab47 \
        -in $top -x 0 -relx 0.477 -y 0 -rely 0.554 -width 0 -relwidth 0.238 \
        -height 0 -relheight 0.22 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

