#############################################################################
# Generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#  Mar 24, 2021 10:32:26 AM IST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m49" -background #000040 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 1280x686+212+135
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3004 1913
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Search" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    menu $top.m49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    ttk::separator $top.tSe97 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe97" "TSeparator3" vTcl:WidgetProc "Search" 1
    ttk::separator $top.tSe100 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe100" "TSeparator4" vTcl:WidgetProc "Search" 1
    frame $top.fra48 \
        -borderwidth 2 -relief groove -background #00002b -height 304 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 795 
    vTcl:DefineAlias "$top.fra48" "Frame_f" vTcl:WidgetProc "Search" 1
    set site_3_0 $top.fra48
    label $site_3_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black -anchor nw \
        -background #00002b -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #bcfbfe -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text Product_Name 
    vTcl:DefineAlias "$site_3_0.lab50" "Product_l" vTcl:WidgetProc "Search" 1
    label $site_3_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black -background #00002b \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 19 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #aaffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text Cost 
    vTcl:DefineAlias "$site_3_0.lab48" "Cost_l" vTcl:WidgetProc "Search" 1
    button $site_3_0.but53 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #eb0214 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Cancel 
    vTcl:DefineAlias "$site_3_0.but53" "Cancel_b" vTcl:WidgetProc "Search" 1
    button $site_3_0.but54 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #00c6c6 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 22 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Pay 
    vTcl:DefineAlias "$site_3_0.but54" "Pay_b" vTcl:WidgetProc "Search" 1
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -relx 0.038 -y 0 -rely 0.099 -width 0 \
        -relwidth 0.961 -height 0 -relheight 0.372 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.553 -y 0 -rely 0.099 -width 0 \
        -relwidth 0.336 -height 0 -relheight 0.289 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but53 \
        -in $site_3_0 -x 0 -relx 0.553 -y 0 -rely 0.724 -width 117 \
        -relwidth 0 -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but54 \
        -in $site_3_0 -x 0 -relx 0.742 -y 0 -rely 0.691 -width 157 \
        -relwidth 0 -height 54 -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tSe97 \
        -in $top -x 0 -relx 0.165 -y 0 -rely 0.167 -width 0 -relwidth 0.001 \
        -height 0 -relheight 0.846 -anchor nw -bordermode inside 
    place $top.tSe100 \
        -in $top -x 0 -relx 0.818 -y 0 -rely 0.167 -width 0 -relwidth 0.001 \
        -height 0 -relheight 0.836 -anchor nw -bordermode inside 
    place $top.fra48 \
        -in $top -x 0 -relx 0.18 -y 0 -rely 0.364 -width 0 -relwidth 0.621 \
        -height 0 -relheight 0.443 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

