#############################################################################
# Generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#  Mar 24, 2021 12:06:02 PM IST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m49" -background #000040 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 1280x686+263+199
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3004 1913
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Ticket" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    menu $top.m49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    ttk::separator $top.tSe97 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe97" "TSeparator3" vTcl:WidgetProc "Ticket" 1
    ttk::separator $top.tSe100 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe100" "TSeparator4" vTcl:WidgetProc "Ticket" 1
    frame $top.fra48 \
        -borderwidth 2 -relief groove -background #00002b -height 425 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 795 
    vTcl:DefineAlias "$top.fra48" "Movie1" vTcl:WidgetProc "Ticket" 1
    set site_3_0 $top.fra48
    label $site_3_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black -background #00002b \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 22 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #bcfbfe -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -wraplength 600 
    vTcl:DefineAlias "$site_3_0.lab50" "Description1" vTcl:WidgetProc "Ticket" 1
    label $site_3_0.lab57 \
        -background #00002b -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 17 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -text {Your Ticket number is: } -wraplength 600 
    vTcl:DefineAlias "$site_3_0.lab57" "Label2" vTcl:WidgetProc "Ticket" 1
    button $site_3_0.but59 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #b4eafe -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Home 
    vTcl:DefineAlias "$site_3_0.but59" "Continue_b" vTcl:WidgetProc "Ticket" 1
    label $site_3_0.lab60 \
        -background #00002b -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #77ff8b -text {List of ticket numbers} 
    vTcl:DefineAlias "$site_3_0.lab60" "Label5" vTcl:WidgetProc "Ticket" 1
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -relx 0.214 -y 0 -rely 0.141 -width 0 \
        -relwidth 0.595 -height 0 -relheight 0.193 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 0 -relx 0.05 -y 0 -rely 0.376 -width 0 \
        -relwidth 0.381 -height 0 -relheight 0.285 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but59 \
        -in $site_3_0 -x 0 -relx 0.629 -y 0 -rely 0.8 -width 227 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 0 -relx 0.491 -y 0 -rely 0.447 -width 0 \
        -relwidth 0.37 -height 0 -relheight 0.144 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tSe97 \
        -in $top -x 0 -relx 0.165 -y 0 -rely 0.167 -width 0 -relwidth 0.001 \
        -height 0 -relheight 0.846 -anchor nw -bordermode inside 
    place $top.tSe100 \
        -in $top -x 0 -relx 0.818 -y 0 -rely 0.167 -width 0 -relwidth 0.001 \
        -height 0 -relheight 0.836 -anchor nw -bordermode inside 
    place $top.fra48 \
        -in $top -x 0 -relx 0.18 -y 0 -rely 0.233 -width 0 -relwidth 0.621 \
        -height 0 -relheight 0.62 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

