#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Mar 24, 2021 04:29:51 PM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = AddCinema (root)
    root.mainloop()

w = None
def create_AddCinema(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_AddCinema(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = AddCinema (w)
    return (w, top)

def destroy_AddCinema():
    global w
    w.destroy()
    w = None

class AddCinema:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1280x686+280+126")
        top.minsize(120, 1)
        top.maxsize(3004, 1913)
        top.resizable(1,  1)
        top.title("New Toplevel")
        top.configure(background="#000040")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.TSeparator3 = ttk.Separator(top)
        self.TSeparator3.place(relx=0.165, rely=0.168,  relheight=0.845)
        self.TSeparator3.configure(orient="vertical")

        self.TSeparator4 = ttk.Separator(top)
        self.TSeparator4.place(relx=0.818, rely=0.168,  relheight=0.835)
        self.TSeparator4.configure(orient="vertical")

        self.Logo_image = tk.Label(top)
        self.Logo_image.place(relx=0.234, rely=0.029, height=92, width=124)
        self.Logo_image.configure(activebackground="#f9f9f9")
        self.Logo_image.configure(activeforeground="black")
        self.Logo_image.configure(background="#d9d9d9")
        self.Logo_image.configure(disabledforeground="#a3a3a3")
        self.Logo_image.configure(foreground="#000000")
        self.Logo_image.configure(highlightbackground="#d9d9d9")
        self.Logo_image.configure(highlightcolor="black")
        self.Logo_image.configure(text='''Label''')

        self.Title_l = tk.Label(top)
        self.Title_l.place(relx=0.359, rely=0.044, height=61, width=372)
        self.Title_l.configure(activebackground="#f9f9f9")
        self.Title_l.configure(activeforeground="black")
        self.Title_l.configure(background="#000040")
        self.Title_l.configure(disabledforeground="#a3a3a3")
        self.Title_l.configure(font="-family {Segoe UI} -size 22")
        self.Title_l.configure(foreground="#ffffff")
        self.Title_l.configure(highlightbackground="#d9d9d9")
        self.Title_l.configure(highlightcolor="black")
        self.Title_l.configure(text='''Theatre Buzz Admin Page''')

        self.Theatre_l = tk.Label(top)
        self.Theatre_l.place(relx=0.203, rely=0.204, height=31, width=284)
        self.Theatre_l.configure(activebackground="#f9f9f9")
        self.Theatre_l.configure(activeforeground="black")
        self.Theatre_l.configure(anchor='w')
        self.Theatre_l.configure(background="#000040")
        self.Theatre_l.configure(disabledforeground="#a3a3a3")
        self.Theatre_l.configure(font="-family {Segoe UI} -size 13")
        self.Theatre_l.configure(foreground="#ffffff")
        self.Theatre_l.configure(highlightbackground="#d9d9d9")
        self.Theatre_l.configure(highlightcolor="black")
        self.Theatre_l.configure(text='''Enter Cinema name:''')

        self.City_l = tk.Label(top)
        self.City_l.place(relx=0.203, rely=0.335, height=31, width=284)
        self.City_l.configure(activebackground="#f9f9f9")
        self.City_l.configure(activeforeground="black")
        self.City_l.configure(anchor='w')
        self.City_l.configure(background="#000040")
        self.City_l.configure(disabledforeground="#a3a3a3")
        self.City_l.configure(font="-family {Segoe UI} -size 13")
        self.City_l.configure(foreground="#ffffff")
        self.City_l.configure(highlightbackground="#d9d9d9")
        self.City_l.configure(highlightcolor="black")
        self.City_l.configure(text='''Enter City''')

        self.Cinemaname_e = tk.Entry(top)
        self.Cinemaname_e.place(relx=0.203, rely=0.262, height=30
                , relwidth=0.222)
        self.Cinemaname_e.configure(background="white")
        self.Cinemaname_e.configure(disabledforeground="#a3a3a3")
        self.Cinemaname_e.configure(font="TkFixedFont")
        self.Cinemaname_e.configure(foreground="#000000")
        self.Cinemaname_e.configure(highlightbackground="#d9d9d9")
        self.Cinemaname_e.configure(highlightcolor="black")
        self.Cinemaname_e.configure(insertbackground="black")
        self.Cinemaname_e.configure(selectbackground="blue")
        self.Cinemaname_e.configure(selectforeground="white")

        self.City_e = tk.Entry(top)
        self.City_e.place(relx=0.203, rely=0.394, height=30, relwidth=0.222)
        self.City_e.configure(background="white")
        self.City_e.configure(disabledforeground="#a3a3a3")
        self.City_e.configure(font="TkFixedFont")
        self.City_e.configure(foreground="#000000")
        self.City_e.configure(highlightbackground="#d9d9d9")
        self.City_e.configure(highlightcolor="black")
        self.City_e.configure(insertbackground="black")
        self.City_e.configure(selectbackground="blue")
        self.City_e.configure(selectforeground="white")

        self.screens_l = tk.Label(top)
        self.screens_l.place(relx=0.203, rely=0.466, height=31, width=284)
        self.screens_l.configure(activebackground="#f9f9f9")
        self.screens_l.configure(activeforeground="black")
        self.screens_l.configure(anchor='w')
        self.screens_l.configure(background="#000040")
        self.screens_l.configure(disabledforeground="#a3a3a3")
        self.screens_l.configure(font="-family {Segoe UI} -size 13")
        self.screens_l.configure(foreground="#ffffff")
        self.screens_l.configure(highlightbackground="#d9d9d9")
        self.screens_l.configure(highlightcolor="black")
        self.screens_l.configure(text='''Enter No of screens:''')

        self.Createcinema_b = tk.Button(top)
        self.Createcinema_b.place(relx=0.594, rely=0.7, height=84, width=207)
        self.Createcinema_b.configure(activebackground="#ececec")
        self.Createcinema_b.configure(activeforeground="#000000")
        self.Createcinema_b.configure(background="#77eaea")
        self.Createcinema_b.configure(disabledforeground="#a3a3a3")
        self.Createcinema_b.configure(cursor="hand2")
        self.Createcinema_b.configure(font="-family {Segoe UI} -size 23")
        self.Createcinema_b.configure(foreground="#000000")
        self.Createcinema_b.configure(highlightbackground="#d9d9d9")
        self.Createcinema_b.configure(highlightcolor="black")
        self.Createcinema_b.configure(pady="0")
        self.Createcinema_b.configure(text='''Create Cinema''')

        self.ScreensSpinbox1 = tk.Spinbox(top, from_=1.0, to=20.0)
        self.ScreensSpinbox1.place(relx=0.367, rely=0.466, relheight=0.044
                , relwidth=0.034)
        self.ScreensSpinbox1.configure(activebackground="#f9f9f9")
        self.ScreensSpinbox1.configure(background="white")
        self.ScreensSpinbox1.configure(buttonbackground="#d9d9d9")
        self.ScreensSpinbox1.configure(disabledforeground="#a3a3a3")
        self.ScreensSpinbox1.configure(font="TkDefaultFont")
        self.ScreensSpinbox1.configure(foreground="black")
        self.ScreensSpinbox1.configure(highlightbackground="black")
        self.ScreensSpinbox1.configure(highlightcolor="black")
        self.ScreensSpinbox1.configure(insertbackground="black")
        self.ScreensSpinbox1.configure(selectbackground="blue")
        self.ScreensSpinbox1.configure(selectforeground="white")

if __name__ == '__main__':
    vp_start_gui()


