#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Mar 24, 2021 11:04:04 AM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = IfAdult (root)
    root.mainloop()

w = None
def create_IfAdult(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_IfAdult(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = IfAdult (w)
    return (w, top)

def destroy_IfAdult():
    global w
    w.destroy()
    w = None

class IfAdult:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1280x686+212+135")
        top.minsize(120, 1)
        top.maxsize(3004, 1913)
        top.resizable(1,  1)
        top.title("New Toplevel")
        top.configure(background="#000040")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.TSeparator3 = ttk.Separator(top)
        self.TSeparator3.place(relx=0.165, rely=0.168,  relheight=0.845)
        self.TSeparator3.configure(orient="vertical")

        self.TSeparator4 = ttk.Separator(top)
        self.TSeparator4.place(relx=0.818, rely=0.168,  relheight=0.835)
        self.TSeparator4.configure(orient="vertical")

        self.Movie1 = tk.Frame(top)
        self.Movie1.place(relx=0.18, rely=0.233, relheight=0.62, relwidth=0.621)
        self.Movie1.configure(relief='groove')
        self.Movie1.configure(borderwidth="2")
        self.Movie1.configure(relief="groove")
        self.Movie1.configure(background="#00002b")
        #self.Movie1.configure(cursor="hand2")
        self.Movie1.configure(highlightbackground="#d9d9d9")
        self.Movie1.configure(highlightcolor="black")

        self.Description1 = tk.Label(self.Movie1)
        self.Description1.place(relx=0.126, rely=0.141, height=142, width=674)
        self.Description1.configure(activebackground="#f9f9f9")
        self.Description1.configure(activeforeground="black")
        self.Description1.configure(anchor='nw')
        self.Description1.configure(background="#00002b")
        self.Description1.configure(disabledforeground="#a3a3a3")
        self.Description1.configure(font="-family {Segoe UI} -size 17")
        self.Description1.configure(foreground="#bcfbfe")
        self.Description1.configure(highlightbackground="#d9d9d9")
        self.Description1.configure(highlightcolor="black")
        self.Description1.configure(text='''Warning: The movie you are trying to book is for Adults only. Please make sure that the people along with you are Adults aswell''')
        self.Description1.configure(wraplength="600")

        self.Label2 = tk.Label(self.Movie1)
        self.Label2.place(relx=0.126, rely=0.424, height=121, width=593)
        self.Label2.configure(background="#00002b")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Segoe UI} -size 17")
        self.Label2.configure(foreground="#ffffff")
        self.Label2.configure(text='''Else You may not be allowed entry and may result is cancellation of ticket at the Cinema. Theatre Buzz will not be held resposible in any way for cancellation of such tickets.''')
        self.Label2.configure(wraplength="600")

        self.Checkbutton1 = tk.Checkbutton(self.Movie1)
        self.Checkbutton1.place(relx=0.05, rely=0.824, relheight=0.106
                , relwidth=0.366)
        self.Checkbutton1.configure(activebackground="#ececec")
        self.Checkbutton1.configure(activeforeground="#000000")
        self.Checkbutton1.configure(background="#00002b")
        self.Checkbutton1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1.configure(cursor="hand2")
        self.Checkbutton1.configure(font="-family {Segoe UI} -size 13")
        self.Checkbutton1.configure(foreground="red")
        self.Checkbutton1.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1.configure(highlightcolor="black")
        self.Checkbutton1.configure(justify='left')
        self.Checkbutton1.configure(text='''I agree that we all are Adults''')

        self.Button1 = tk.Button(self.Movie1)
        self.Button1.place(relx=0.616, rely=0.847, height=44, width=227)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#b4eafe")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(cursor="hand2")
        self.Button1.configure(font="-family {Segoe UI} -size 14")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Continue''')

if __name__ == '__main__':
    vp_start_gui()


