#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Mar 22, 2021 12:09:57 PM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from home import create_Home, Home

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Regconfirm (root)
    root.mainloop()

w = None
def create_Regconfirm(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Regconfirm(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Regconfirm (w)
    return (w, top)

def destroy_Regconfirm():
    global w
    w.destroy()
    w = None





class Regconfirm:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("497x525+668+155")
        top.minsize(120, 1)
        top.maxsize(3004, 1913)
        top.resizable(1,  1)
        top.title("New Toplevel")
        top.configure(background="#000328")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(x=86, rely=0.114, height=222, width=424)
        self.Label1.configure(background="#000328")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 18")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(text='''Please check your email to Confirm your registration''')
        self.Label1.configure(wraplength="300")

        self.Signin_b = tk.Button(top)
        self.Signin_b.place(relx=0.322, rely=0.629, height=54, width=177)
        self.Signin_b.configure(activebackground="#ececec")
        self.Signin_b.configure(activeforeground="#000000")
        self.Signin_b.configure(background="#2ba5ff")
        self.Signin_b.configure(borderwidth="4")
        self.Signin_b.configure(cursor="fleur")
        self.Signin_b.configure(disabledforeground="#a3a3a3")
        self.Signin_b.configure(font="-family {Segoe UI} -size 14")
        self.Signin_b.configure(foreground="#000000")
        self.Signin_b.configure(highlightbackground="#d9d9d9")
        self.Signin_b.configure(highlightcolor="black")
        self.Signin_b.configure(pady="0")
        self.Signin_b.configure(text='''Go To Sign In''', command=self.new_window)
        
    def new_window(self):
        root.withdraw()
        bb = create_Home(root)

if __name__ == '__main__':
    vp_start_gui()


