#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Mar 23, 2021 05:31:05 PM IST  platform: Windows NT

import sys
from PIL import ImageTk, Image
import PIL
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
    
from tkinter import *

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Search (root)
    root.mainloop()

w = None
def create_Search(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Search(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Search (w)
    return (w, top)

def destroy_Search():
    global w
    w.destroy()
    w = None

class Search:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1280x686+212+135")
        top.minsize(120, 1)
        top.maxsize(3004, 1913)
        top.resizable(1,  1)
        top.title("New Toplevel")
        top.configure(background="#000040")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        global img
        img = ImageTk.PhotoImage(file="bg.png")
        self.Background = tk.Label(top,image = img)        
        self.Background.place(relx=0, rely=0, height=900, width=1200)
        self.Background=img
        
        
        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)



############################################Membership#########################################################

        self.Membership_f = tk.LabelFrame(top)
        self.Membership_f.place(relx=0.013, rely=0.219, relheight=0.516
                , relwidth=0.14)
        self.Membership_f.configure(relief='groove')
        self.Membership_f.configure(foreground="#edea67")
        self.Membership_f.configure(background="#bfe2ff")
        self.Membership_f.configure(highlightbackground="#f3fee2")
        self.Membership_f.configure(highlightcolor="#4bc602")

        self.Platinum_b = tk.Button(self.Membership_f)
        self.Platinum_b.place(relx=0.056, rely=0.452, height=84, width=157
                , bordermode='ignore')
        self.Platinum_b.configure(activebackground="#707070")
        self.Platinum_b.configure(activeforeground="white")
        self.Platinum_b.configure(activeforeground="#000000")
        self.Platinum_b.configure(background="#d8d8d8")
        self.Platinum_b.configure(borderwidth="9")
        self.Platinum_b.configure(disabledforeground="#a3a3a3")
        self.Platinum_b.configure(font="-family {Segoe UI} -size 15")
        self.Platinum_b.configure(foreground="#000000")
        self.Platinum_b.configure(highlightbackground="#d9d9d9")
        self.Platinum_b.configure(highlightcolor="black")
        self.Platinum_b.configure(pady="0")
        self.Platinum_b.configure(text='''Platinum''')

        self.Gold_b = tk.Button(self.Membership_f)
        self.Gold_b.place(relx=0.056, rely=0.734, height=84, width=157
                , bordermode='ignore')
        self.Gold_b.configure(activebackground="#f0df99")
        self.Gold_b.configure(activeforeground="#000000")
        self.Gold_b.configure(background="#ffda04")
        self.Gold_b.configure(borderwidth="9")
        self.Gold_b.configure(disabledforeground="#a3a3a3")
        self.Gold_b.configure(font="-family {Segoe UI} -size 15")
        self.Gold_b.configure(foreground="#000000")
        self.Gold_b.configure(highlightbackground="#d9d9d9")
        self.Gold_b.configure(highlightcolor="black")
        self.Gold_b.configure(pady="0")
        self.Gold_b.configure(text='''Gold''')

        self.Diamond_b = tk.Button(self.Membership_f)
        self.Diamond_b.place(relx=0.061, rely=0.169, height=84, width=157
                , bordermode='ignore')
        self.Diamond_b.configure(activebackground="#d9fcff")
        self.Diamond_b.configure(activeforeground="#7070fa")
        self.Diamond_b.configure(background="#2de9f2")
        self.Diamond_b.configure(borderwidth="9")
        self.Diamond_b.configure(disabledforeground="#a3a3a3")
        self.Diamond_b.configure(font="-family {Segoe UI} -size 15")
        self.Diamond_b.configure(foreground="#000000")
        self.Diamond_b.configure(highlightbackground="#d9d9d9")
        self.Diamond_b.configure(highlightcolor="#e9f552")
        self.Diamond_b.configure(highlightthickness="6")
        self.Diamond_b.configure(pady="0")
        self.Diamond_b.configure(text='''Diamond''')

        self.Join_l = tk.Label(self.Membership_f)
        self.Join_l.place(relx=0.056, rely=0.028, height=41, width=155
                , bordermode='ignore')
        self.Join_l.configure(activebackground="#f9f9f9")
        self.Join_l.configure(activeforeground="black")
        self.Join_l.configure(background="#bfe2ff")
        self.Join_l.configure(disabledforeground="#a3a3a3")
        self.Join_l.configure(font="-family {Segoe UI} -size 12")
        self.Join_l.configure(foreground="#000000")
        self.Join_l.configure(highlightbackground="#d9d9d9")
        self.Join_l.configure(highlightcolor="black")
        self.Join_l.configure(text='''Join our Membership plan!''')
        self.Join_l.configure(wraplength="150")
        
######################################################################################################################################################

#################################################Home######################################################################################

        self.Home_f = tk.LabelFrame(top)
        self.Home_f.place(relx=0.023, rely=0.029, relheight=0.093, relwidth=0.32)

        self.Home_f.configure(relief='groove')
        self.Home_f.configure(foreground="#000000")
        self.Home_f.configure(background="#e8e8ff")
        self.Home_f.configure(highlightbackground="#d9d9d9")
        self.Home_f.configure(highlightcolor="black")

        self.home_inner_f = tk.Frame(self.Home_f)
        self.home_inner_f.place(relx=0.017, rely=0.109, relheight=0.797
                , relwidth=0.959, bordermode='ignore')
        self.home_inner_f.configure(relief='groove')
        self.home_inner_f.configure(borderwidth="2")
        self.home_inner_f.configure(relief="groove")
        self.home_inner_f.configure(background="#b3eaff")
        self.home_inner_f.configure(highlightbackground="#d9d9d9")
        self.home_inner_f.configure(highlightcolor="black")

        self.Home_b = tk.Button(self.home_inner_f)
        self.Home_b.place(relx=0.025, rely=0.0, height=54, width=77)
        self.Home_b.configure(activebackground="#ececec")
        self.Home_b.configure(activeforeground="#000000")
        self.Home_b.configure(background="#000040")
        self.Home_b.configure(disabledforeground="#a3a3a3")
        self.Home_b.configure(font="-family {Segoe UI} -size 12")
        self.Home_b.configure(foreground="#ffffff")
        self.Home_b.configure(highlightbackground="#d9d9d9")
        self.Home_b.configure(highlightcolor="black")
        self.Home_b.configure(pady="0")
        self.Home_b.configure(text='''Home''')

        self.Member_l = tk.Label(self.home_inner_f)
        self.Member_l.place(relx=0.262, rely=0.137, height=34, width=262)
        self.Member_l.configure(activebackground="#b3eaff")
        self.Member_l.configure(activeforeground="black")
        self.Member_l.configure(background="#b3eaff")
        self.Member_l.configure(disabledforeground="#a3a3a3")
        self.Member_l.configure(font="-family {Segoe UI} -size 12")
        self.Member_l.configure(foreground="#000000")
        self.Member_l.configure(highlightbackground="#d9d9d9")
        self.Member_l.configure(highlightcolor="black")
        self.Member_l.configure(text='''Membership status''')


##################################################################################################################################################

###############################################Search##########################################################################################

        self.Search_f = tk.LabelFrame(top)
        self.Search_f.place(relx=0.609, rely=0.044, relheight=0.06
                , relwidth=0.322)
        self.Search_f.configure(relief='groove')
        self.Search_f.configure(foreground="black")
        self.Search_f.configure(background="#e8e8ff")
        self.Search_f.configure(highlightbackground="#d9d9d9")
        self.Search_f.configure(highlightcolor="black")


        self.Search_b = tk.Button(self.Search_f)
        self.Search_b.place(relx=0.0, rely=0.0, height=44, width=100
                , bordermode='ignore')
        self.Search_b.configure(activebackground="#b3eaff")
        self.Search_b.configure(activeforeground="#000000")
        self.Search_b.configure(background="#00205b")
        self.Search_b.configure(disabledforeground="#a3a3a3")
        self.Search_b.configure(cursor="hand2")
        self.Search_b.configure(font="-family {Segoe UI} -size 12")
        self.Search_b.configure(foreground="#ffffff")
        self.Search_b.configure(highlightbackground="#d9d9d9")
        self.Search_b.configure(highlightcolor="black")
        self.Search_b.configure(pady="0")
        self.Search_b.configure(text='''Search''')

        self.Search_e = tk.Entry(self.Search_f)
        self.Search_e.place(relx=0.25, rely=0.1, height=38, relwidth=0.745
                , bordermode='ignore')
        self.Search_e.configure(background="white")
        self.Search_e.configure(disabledforeground="#a3a3a3")
        self.Search_e.configure(font="-family {Segoe UI} -size 12")
        self.Search_e.configure(foreground="#000000")
        self.Search_e.configure(highlightbackground="#d9d9d9")
        self.Search_e.configure(highlightcolor="black")
        self.Search_e.configure(insertbackground="black")
        self.Search_e.configure(selectbackground="blue")
        self.Search_e.configure(selectforeground="white")

###############################################################################################################################################



        self.TSeparator3 = ttk.Separator(top)
        self.TSeparator3.place(relx=0.165, rely=0.168,  relheight=0.845)
        self.TSeparator3.configure(orient="vertical")

        self.TSeparator4 = ttk.Separator(top)
        self.TSeparator4.place(relx=0.818, rely=0.168,  relheight=0.835)
        self.TSeparator4.configure(orient="vertical")


################################################################Result instance############################################################
        self.Movie1 = tk.Frame(top)
        self.Movie1.place(relx=0.18, rely=0.233, relheight=0.138, relwidth=0.621)

        self.Movie1.configure(relief='groove')
        self.Movie1.configure(borderwidth="2")
        self.Movie1.configure(relief="groove")
        self.Movie1.configure(background="#00002b")

        self.Image1 = tk.Label(self.Movie1)
        self.Image1.place(relx=0.025, rely=0.095, height=73, width=135)
        self.Image1.configure(background="#d9d9d9")
        self.Image1.configure(disabledforeground="#a3a3a3")
        self.Image1.configure(foreground="#000000")
        self.Image1.configure(text='''image''')

        self.Description1 = tk.Label(self.Movie1)
        self.Description1.place(relx=0.239, rely=0.095, height=73, width=573)
        self.Description1.configure(anchor='nw')
        self.Description1.configure(background="#00002b")
        self.Description1.configure(cursor="fleur")
        self.Description1.configure(disabledforeground="#a3a3a3")
        self.Description1.configure(font="-family {Segoe UI} -size 12")
        self.Description1.configure(foreground="#bcfbfe")
        self.Description1.configure(text='''description''')

##############################################################################################################################################

##################################################################scroller########################################################
        self.Previous = tk.Button(top)
        self.Previous.place(relx=0.383, rely=0.933, height=24, width=47)
        self.Previous.configure(activebackground="#ececec")
        self.Previous.configure(activeforeground="#000000")
        self.Previous.configure(background="#b4eafe")
        self.Previous.configure(disabledforeground="#a3a3a3")
        self.Previous.configure(font="-family {Segoe UI} -size 15")
        self.Previous.configure(foreground="#000000")
        self.Previous.configure(highlightbackground="#d9d9d9")
        self.Previous.configure(highlightcolor="black")
        self.Previous.configure(pady="0")
        self.Previous.configure(text='''<''')

        self.Next = tk.Button(top)
        self.Next.place(relx=0.57, rely=0.933, height=24, width=47)
        self.Next.configure(activebackground="#ececec")
        self.Next.configure(activeforeground="#000000")
        self.Next.configure(background="#b4eafe")
        self.Next.configure(disabledforeground="#a3a3a3")
        self.Next.configure(font="-family {Segoe UI} -size 15")
        self.Next.configure(foreground="#000000")
        self.Next.configure(highlightbackground="#d9d9d9")
        self.Next.configure(highlightcolor="black")
        self.Next.configure(pady="0")
        self.Next.configure(text='''>''')

        self.Page_list = tk.Label(top)
        self.Page_list.place(relx=0.43, rely=0.933, height=21, width=164)
        self.Page_list.configure(activebackground="#f0f0f0f0f0f0")
        self.Page_list.configure(background="#000040")
        self.Page_list.configure(disabledforeground="#a3a3a3")
        self.Page_list.configure(font="-family {Segoe UI} -size 12")
        self.Page_list.configure(foreground="#b4eafe")
        self.Page_list.configure(text='''1 of 4''')


#####################################################################################################################################

if __name__ == '__main__':
    vp_start_gui()


