#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Mar 24, 2021 09:14:49 AM IST  platform: Windows NT

import sys
from searchbar import Searchbar
from memberbar import Memberbar
from homebar import Homebar
from sidebar import Sidebar

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Slots (root)
    root.mainloop()

w = None
def create_Slots(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Slots(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Slots (w)
    return (w, top)

def destroy_Slots():
    global w
    w.destroy()
    w = None

class Slots(Searchbar, Memberbar, Homebar):
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1280x686+212+135")
        top.minsize(120, 1)
        top.maxsize(3004, 1913)
        top.resizable(1,  1)
        top.title("New Toplevel")
        top.configure(background="#000040")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Recommended_l = tk.Label(top)
        self.Recommended_l.place(relx=0.172, rely=0.131, height=48, width=204)
        self.Recommended_l.configure(activebackground="#f9f9f9")
        self.Recommended_l.configure(activeforeground="black")
        self.Recommended_l.configure(background="#000040")
        self.Recommended_l.configure(borderwidth="5")
        self.Recommended_l.configure(disabledforeground="#a3a3a3")
        self.Recommended_l.configure(font="-family {Segoe UI} -size 22")
        self.Recommended_l.configure(foreground="#ffffff")
        self.Recommended_l.configure(highlightbackground="#d9d9d9")
        self.Recommended_l.configure(highlightcolor="black")
        self.Recommended_l.configure(text='''Recommended!''')

        self.TSeparator3 = ttk.Separator(top)
        self.TSeparator3.place(relx=0.165, rely=0.168,  relheight=0.845)
        self.TSeparator3.configure(orient="vertical")

        self.TSeparator4 = ttk.Separator(top)
        self.TSeparator4.place(relx=0.818, rely=0.168,  relheight=0.835)
        self.TSeparator4.configure(orient="vertical")

        self.Movie1 = tk.Frame(top)
        self.Movie1.place(relx=0.18, rely=0.364, relheight=0.137, relwidth=0.621)

        self.Movie1.configure(relief='groove')
        self.Movie1.configure(borderwidth="2")
        self.Movie1.configure(relief="groove")
        self.Movie1.configure(background="#00002b")
        self.Movie1.configure(highlightbackground="#d9d9d9")
        self.Movie1.configure(highlightcolor="black")

        self.Description1 = tk.Label(self.Movie1)
        self.Description1.place(relx=0.025, rely=0.106, height=32, width=764)
        self.Description1.configure(activebackground="#f9f9f9")
        self.Description1.configure(activeforeground="black")
        self.Description1.configure(anchor='nw')
        self.Description1.configure(background="#00002b")
        self.Description1.configure(cursor="fleur")
        self.Description1.configure(disabledforeground="#a3a3a3")
        self.Description1.configure(font="-family {Segoe UI} -size 12")
        self.Description1.configure(foreground="#bcfbfe")
        self.Description1.configure(highlightbackground="#d9d9d9")
        self.Description1.configure(highlightcolor="black")
        self.Description1.configure(text='''Name of cinema with address''')

        self.Label3 = tk.Label(self.Movie1)
        self.Label3.place(relx=0.038, rely=0.638, height=21, width=54)
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''timings''')

        self.Label4 = tk.Label(self.Movie1)
        self.Label4.place(relx=0.138, rely=0.638, height=21, width=55)
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''timings''')

        self.Previous = tk.Button(top)
        self.Previous.place(relx=0.383, rely=0.933, height=24, width=47)
        self.Previous.configure(activebackground="#ececec")
        self.Previous.configure(activeforeground="#000000")
        self.Previous.configure(background="#b4eafe")
        self.Previous.configure(disabledforeground="#a3a3a3")
        self.Previous.configure(font="-family {Segoe UI} -size 15")
        self.Previous.configure(foreground="#000000")
        self.Previous.configure(highlightbackground="#d9d9d9")
        self.Previous.configure(highlightcolor="black")
        self.Previous.configure(pady="0")
        self.Previous.configure(text='''<''')

        self.Next = tk.Button(top)
        self.Next.place(relx=0.57, rely=0.933, height=24, width=47)
        self.Next.configure(activebackground="#ececec")
        self.Next.configure(activeforeground="#000000")
        self.Next.configure(background="#b4eafe")
        self.Next.configure(disabledforeground="#a3a3a3")
        self.Next.configure(font="-family {Segoe UI} -size 15")
        self.Next.configure(foreground="#000000")
        self.Next.configure(highlightbackground="#d9d9d9")
        self.Next.configure(highlightcolor="black")
        self.Next.configure(pady="0")
        self.Next.configure(text='''>''')

        self.Page_list = tk.Label(top)
        self.Page_list.place(relx=0.43, rely=0.933, height=21, width=164)
        self.Page_list.configure(activebackground="#f0f0f0f0f0f0")
        self.Page_list.configure(activeforeground="black")
        self.Page_list.configure(background="#000040")
        self.Page_list.configure(disabledforeground="#a3a3a3")
        self.Page_list.configure(font="-family {Segoe UI} -size 12")
        self.Page_list.configure(foreground="#b4eafe")
        self.Page_list.configure(highlightbackground="#d9d9d9")
        self.Page_list.configure(highlightcolor="black")
        self.Page_list.configure(text='''1 of 4''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.461, rely=0.248, height=51, width=74)
        self.Label2.configure(background="#000040")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Segoe UI} -size 16")
        self.Label2.configure(foreground="#bbfcff")
        self.Label2.configure(text='''Date''')

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.391, rely=0.262, height=44, width=47)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#5bedf9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI} -size 18")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''<''')

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.555, rely=0.262, height=44, width=47)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#5bedf9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font="-family {Segoe UI} -size 18")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''>''')
        
        Searchbar.__init__(self, top=None)
        Memberbar.__init__(self, top=None)
        Homebar.__init__(self, top=None)
        Sidebar.__init__(self, top=None)

if __name__ == '__main__':
    vp_start_gui()


